<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <UserSecretsId>52bc94c1-eb20-4703-9b7d-3799f61099df</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\CoinKeeper.Logging\CoinKeeper.Logging.csproj" />
      <ProjectReference Include="..\Authentication\CoinKeeper.Authentication\CoinKeeper.Authentication.csproj" />
      <ProjectReference Include="..\CoinKeeper.Finance\CoinKeeper.Finance.csproj" />
      <ProjectReference Include="..\Common\CoinKeeper.Common\CoinKeeper.Common.csproj" />
      <ProjectReference Include="..\Common\CoinKeeper.Infrastructure\CoinKeeper.Infrastructure.csproj" />
    </ItemGroup>

</Project>
