<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
  
    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="14.0.0" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
      <PackageReference Include="NSwag.AspNetCore" Version="14.4.0" />
      <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
      <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="8.1.1" />
    </ItemGroup>
  
    <ItemGroup>
      <ProjectReference Include="..\..\Authentication\CoinKeeper.Authentication.Domain\CoinKeeper.Authentication.Domain.csproj" />
      <ProjectReference Include="..\CoinKeeper.Common.Domain\CoinKeeper.Common.Domain.csproj" />
      <ProjectReference Include="..\CoinKeeper.Infrastructure\CoinKeeper.Infrastructure.csproj" />
    </ItemGroup>

</Project>
